DROP SCHEMA KURSOVOY;
CREATE SCHEMA KURSOVOY;
use KURSOVOY;
CREATE TABLE USERS
(
    USER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(45) NOT NULL,
    LAST_NAME VARCHAR(45) NOT NULL,
    AGE INT,
    LOGIN VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(45) NOT NULL,
    FAIL_LOGIN_COUNT INT DEFAULT 0 NOT NULL,
    STATUS INT DEFAULT 1 NOT NULL,
    LAST_LOGIN_DATE TIMESTAMP,
    SMS_CODE VARCHAR(4),
    PHONE VARCHAR(32)
);
CREATE TABLE USER_IP_HISTORY
(
    USER_IP_HISTORY_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    USER_ID INT NOT NULL,
    IP_ADDRESS VARCHAR(45) NOT NULL,
    LOGIN_STATUS INT DEFAULT 0 NOT NULL,
    LOGIN_TIME TIMESTAMP,
    USER_AGENT VARCHAR(512),
    LOCATION VARCHAR(45)
);
INSERT INTO KURSOVOY.USERS (USER_ID, FIRST_NAME, LAST_NAME, AGE, LOGIN, PASSWORD, FAIL_LOGIN_COUNT, STATUS, LAST_LOGIN_DATE, SMS_CODE, PHONE) VALUES (7, 'User', 'Admin', 5, 'admin', 'MTIzNA==', 0, 0, null, null, '');

