USE KURSOVOY;

ALTER TABLE USERS
ADD COLUMN FAIL_LOGIN_COUNT INT(11) NOT NULL DEFAULT 0 AFTER PASSWORD,
ADD COLUMN STATUS INT(11) NOT NULL DEFAULT 1 AFTER FAIL_LOGIN_COUNT,
ADD COLUMN LAST_LOGIN_DATE TIMESTAMP NULL AFTER STATUS;
