use KURSOVOY;
CREATE TABLE .USER_IP_HISTORY (
  USER_IP_HISTORY_ID INT NOT NULL,
  USER_ID INT NOT NULL,
  IP_ADDRESS VARCHAR(45) NOT NULL,
  PRIMARY KEY (USER_IP_HISTORY_ID));
COMMIT ;
  
ALTER TABLE USER_IP_HISTORY
ADD COLUMN LOGIN_STATUS INT(11) NOT NULL AFTER IP_ADDRESS,
ADD COLUMN LOGIN_TIME TIMESTAMP NULL AFTER LOGIN_STATUS;

COMMIT ;
