use KURSOVOY;
CREATE TABLE CONTENT_STORAGE
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    COURSE_ID INT NOT NULL,
    TYPE VARCHAR(20) NOT NULL,
    CONTENT MEDIUMTEXT,
    NAME VARCHAR(100)
);